name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Restore Preview JSON Cache
        uses: actions/cache@v4
        with:
          path: public/json/preview
          key: ${{ runner.os }}-og-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-og-cache-

      - run: npm i --force

      - name: Create env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build VitePress site
        run: npm run build

      - name: Create Redirects
        run: |
          npx tsx scripts/create-moved-redirects.ts

      - name: Prepare Deployment Directory
        run: |
          mkdir -p .vitepress/dist/json/preview
          if [ -d "public/json/preview" ] && [ "$(ls -A public/json/preview)" ]; then
            cp -r public/json/preview/* .vitepress/dist/json/preview/
          fi

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: .vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
